name: '✨ Feature Request'
description: Feature request
title: '[Feature]: '
labels: ['feature request']
assignees:
  - Kuingsmile
body:
  - type: markdown
    attributes:
      value: |+
        ## Word GPT Plus Issue Template
        Please submit your request using this template, otherwise it may be closed.
        **Before asking a question, make sure you've read the FAQ, documentation, and closed issues.**
  - type: checkboxes
    id: read
    attributes:
      label: Pre-reading
      description:
        I have searched and read the following (please tick after reading)
      options:
        - label: '[Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)'
          required: true
        - label: '[README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)'
          required: true
  - type: dropdown
    id: service
    attributes:
      label: Service Type
      options:
        - Official hosted service
        - Self-hosted service
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: System Information
      options:
        - Windows
        - Mac
        - Mac(arm64)
        - Linux
        - All
    validations:
      required: true
  - type: dropdown
    id: office
    attributes:
      label: Office Version
      options:
        - office 2016 retail
        - office 2019 retail
        - office 2021
        - microsoft 365
        - others
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Feature Request
      description:
        Describe the feature you want or improvements to existing features.
    validations:
      required: true
